---
root: true
env:
  es2022: true
  node: true
ignorePatterns:
  - /node_modules/**/*
  - /dist/**/*
  - /scripts/**/*.js
  - /tmp/**/*
  - /vitest.config.ts
extends:
  - eslint:recommended
  - standard-with-typescript
  - prettier
plugins:
  - '@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
rules:
  semi: off
  no-unused-vars:
    - error
    - vars: all
      args: none
      varsIgnorePattern: '^_'
  react/display-name: off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-unnecessary-condition': error
  '@typescript-eslint/restrict-template-expressions':
    - error
    - allowNumber: true
      allowBoolean: true
      allowAny: true
      allowNullish: false
      allowRegExp: true
